name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: check
        run: ./gradlew jvmTest

  documentation:
    name: publish docs
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate api docs with dokka
        env:
          GIT_TAG_VERSION: ${{ github.ref_name }}
        run: ./gradlew dokkaHtml
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/build/dokka/html
      - name: Release to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  publish:
    name: publish package
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: publish
        env:
          GIT_TAG_VERSION: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVEN_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
        run: ./gradlew publish